spring.application.name=summary-app

server.port=80

spring.profiles.active=standalone
spring.main.banner-mode=off
spring.devtools.add-properties=true

groq.api.url=https://api.groq.com/openai
qroq.api.key=${API_KEY_GROQ}


spring.datasource.url=jdbc:postgresql://localhost:15432/page-summary-database
spring.datasource.username=maciek
spring.datasource.password=secret
##default##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.jpa.open-in-view=false

logging.level.devemm=DEBUG


spring.docker.compose.file=compose-dev.yaml
spring.docker.compose.lifecycle-management=start_only
